/* resource set indices for DIAL */

#define DIAL       0 /* form/dialog */
#define FILL       2 /* BOX in tree DIAL */
#define VSLID      3 /* BOX in tree DIAL */
#define DOWN       4 /* BOXCHAR in tree DIAL */
#define UP         5 /* BOXCHAR in tree DIAL */
#define BBS1       6 /* BOXTEXT in tree DIAL */
#define BBS2       7 /* BOXTEXT in tree DIAL */
#define BBS3       8 /* BOXTEXT in tree DIAL */
#define BBS4       9 /* BOXTEXT in tree DIAL */
#define BBS5      10 /* BOXTEXT in tree DIAL */
#define BBS6      11 /* BOXTEXT in tree DIAL */
#define BBS7      12 /* BOXTEXT in tree DIAL */
#define ABOUT     14 /* BUTTON in tree DIAL */
#define DIALER    15 /* BUTTON in tree DIAL */
#define CANCEL    16 /* BUTTON in tree DIAL */
#define SETUP     17 /* BUTTON in tree DIAL */
#define ADD       18 /* BUTTON in tree DIAL */

#define INFO       1 /* form/dialog */

#define SETTINGS   2 /* form/dialog */
#define NAME       1 /* FBOXTEXT in tree SETTINGS */
#define NUMBER     2 /* FBOXTEXT in tree SETTINGS */
#define SAVE       3 /* BUTTON in tree SETTINGS */
#define REDIAL     4 /* FBOXTEXT in tree SETTINGS */
#define DELETE     7 /* BUTTON in tree SETTINGS */
#define OK         8 /* BUTTON in tree SETTINGS */

